zevnda/steam-game-idler

- components/UpdateScreen.jsx
- components/Window.jsx
- components/automation/CardFarming.jsx
- components/gameslist/GameIdleList.jsx
- components/gameslist/GamesList.jsx
- components/gameslist/GamesWithDrops.jsx
- components/gameslist/PageHeader.jsx
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
- Updates will now be handled inline
- Now, when an update for SGI is available, you will see an updating screen while the update in automatically downloaded in the background, rather than the previous dialog prompt
- Because of this change, there will no longer be a `portable` version of SGI in any future releases
> Feat(handle updates inline)

- components/automation/CardFarming.jsx
- components/gameslist/GameIdleList.jsx
- components/gameslist/GamesList.jsx
- components/gameslist/GamesWithDrops.jsx
- components/gameslist/PageHeader.jsx
- src-tauri/tauri.conf.json
- Adds an `Add All Games With Drops` when your `sort` filter is set to `Card Farming Games`
- This will find all games in your Steam library that have 1 or more card drops remaining and add them all to your `Card Farming List`
> feat(Added an 'add all games with drops remaining' button)

- components/Window.jsx
- components/automation/AchievementUnlocker.jsx
- components/gameslist/Automate.jsx
- components/gameslist/CardMenu.jsx
- components/gameslist/GameAchievementList.jsx
- components/gameslist/GameIdleList.jsx
- components/settings/AchievementSettings.jsx
- components/settings/Settings.jsx
- components/settings/SettingsMenu.jsx
- Added a `skip hidden achievements` option to the `achievement unlocker` settings
> feat(skip hidden achievements)

- components/Header.jsx
- components/achievements/Achievements.jsx
- components/achievements/AchievementsList.jsx
- components/achievements/Alerts.jsx
- components/achievements/BulkButtons.jsx
- components/achievements/PageHeader.jsx
- components/achievements/StatisticsList.jsx
- components/settings/AchievementSettings.jsx
- components/settings/Logs.jsx
- components/settings/SettingsMenu.jsx
- libs/steam-utility/Program.cs
- src-tauri/src/main.rs
- utils/utils.js
- Added a tab to the `achievement manager` screen called `statistics` which allows users to edit game achievement statistics
> Feat(edit achievement statistics)

- CHANGELOG.md
- src-tauri/src/game_data.rs
- src-tauri/src/main.rs
- src/components/customlists/CustomList.jsx
- src/components/customlists/ManualAdd.jsx
- src/hooks/customlists/useManualAdd.js
> #81: Re-added the `manual add` button

- CHANGELOG.md
- src/components/customlists/CustomList.jsx
- src/components/customlists/EditListModal.jsx
- src/components/customlists/ManualAdd.jsx
- src/hooks/customlists/useManualAdd.js
> #81: Make the `manual add` button available for all custom list

- src/components/automation/CardFarming.jsx
- src/hooks/automation/useCardFarming.js
- src/utils/utils.js
> #88: fix stop idle uint error

- CHANGELOG.md
- src-tauri/src/tasks.rs
- src-tauri/src/utils.rs
- src/components/automation/CardFarming.jsx
- src/hooks/automation/useCardFarming.js
- src/utils/utils.js
> #90: potential fix for card farming buffer overflow

- CHANGELOG.md
- src-tauri/src/tasks.rs
> #90: improve `stop_idle` function

- CHANGELOG.md
- src/components/automation/AchievementUnlocker.jsx
> Fix achievement unlocker getting stuck at one second

- CHANGELOG.md
- src-tauri/src/lib.rs
- src-tauri/src/tasks.rs
- src/components/gameslist/FreeGamesList.jsx
- src/components/gameslist/IdlingGamesList.jsx
- src/components/gameslist/PageHeader.jsx
- src/components/ui/GameCard.jsx
- src/hooks/layout/useWindow.js
- src/styles/globals.css
- src/utils/gameslist/gameCardHandler.js
- src/utils/utils.js
> Improve overall handling of currently idling games

- CHANGELOG.md
- src-tauri/src/process_handler.rs
> Fix invalid utf-8 sequence error

- src/i18n/locales/it/translation.json
i added the italian translation, some terms are still in english because in italian videogame slang there's no translation
> added italian translation

- latest.json
- src-tauri/tauri.conf.json
Automated version bump for release v1.9.7 by workflow run #14103897647
> chore(version): bump to 1.9.7

- latest.json
- src-tauri/tauri.conf.json
Automated version bump for release v1.9.8 by workflow run #14106449638
> chore(version): bump to 1.9.8

- latest.json
- src-tauri/tauri.conf.json
Automated version bump for release v1.9.9 by workflow run #14120582044
> chore(version): bump to 1.9.9

- latest.json
- src-tauri/tauri.conf.json
Automated version bump for release v1.9.10 by workflow run #14124047359
> chore(version): bump to 1.9.10

- src-tauri/src/user_data.rs
> fix(tauri-user-data): improve `get_users` command to account for lowercase prop names

- CHANGELOG.md
- src-tauri/src/trading_cards.rs
- src/components/settings/GeneralSettings.tsx
- src/components/trading-cards/PriceData.tsx
- src/components/ui/i18n/CurrencySwitch.tsx
- src/hooks/trading-cards/useTradingCardsList.ts
- src/i18n/locales/en-US/translation.json
> feat(settings): add currency select menu

- CHANGELOG.md
- package.json
- src-tauri/src/idling.rs
- src/components/automation/CardFarming.tsx
- src/hooks/automation/useCardFarming.ts
- src/utils/idle.ts
> fix(card-farming): incorrectly displayed game names

- src-tauri/src/trading_cards.rs
- src/components/trading-cards/PageHeader.tsx
- src/components/trading-cards/PriceData.tsx
- src/components/trading-cards/PriceInput.tsx
- src/components/trading-cards/TradingCardsList.tsx
- src/hooks/trading-cards/useTradingCardsList.ts
> fix(trading-card-manager): account for steam fees when listing trading cards

- CHANGELOG.md
- src/hooks/layout/useWindow.ts
> fix(auto-idle): implement better checks to ensure steam is running

- CHANGELOG.md
- docs/src/content/settings/general.mdx
- src-tauri/src/game_data.rs
- src-tauri/src/lib.rs
- src-tauri/src/settings.rs
- src/components/contexts/UserContext.tsx
- src/components/settings/GeneralSettings.tsx
- src/hooks/layout/useWindow.ts
- src/i18n/locales/en-US/translation.json
- src/types/settings.ts
> feat(settings): add start minimized setting

- CHANGELOG.md
- src/components/settings/Settings.tsx
- src/components/ui/SideBar.tsx
> refactor(ui): add disabled state to buttons during automation

- CHANGELOG.md
- src-tauri/src/automation.rs
> fix: card drops error for large games lists

- CHANGELOG.md
- src-tauri/src/trading_cards.rs
> fix(trading-card-manager): bad request error in gettradingcards

- CHANGELOG.md
- src-tauri/src/user_data.rs
- src/hooks/layout/useSetup.ts
> fix(setup): improve method for getting user summaries

- CHANGELOG.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/process_handler.rs
- src-tauri/src/utils.rs
- src/components/achievements/PageHeader.tsx
> refactor(tauri): improve method for tracking idling processes

- CHANGELOG.md
- src/components/achievements/AchievementButtons.tsx
- src/components/achievements/Achievements.tsx
- src/components/achievements/AchievementsList.tsx
- src/components/achievements/StatisticButtons.tsx
- src/components/achievements/StatisticsList.tsx
- src/hooks/achievements/useAchievements.ts
> refactor(achievement-manager): add refresh button

- SECURITY.md
- docs/app/components/landing/FooterSection.tsx
> docs: show year range in footer

- CHANGELOG.md
- src-tauri/Cargo.toml
- src-tauri/src/achievement_manager.rs
- src-tauri/src/custom_lists.rs
- src-tauri/src/game_data.rs
- src-tauri/src/lib.rs
- src-tauri/src/logging.rs
- src-tauri/src/settings.rs
- src-tauri/src/trading_cards.rs
- src-tauri/src/user_data.rs
- src-tauri/src/utils.rs
- src/components/contexts/StateContext.tsx
- src/components/settings/ExportSettings.tsx
- src/components/settings/OpenSettings.tsx
- src/components/trading-cards/TradingCardsList.tsx
- src/components/ui/SideBar.tsx
- src/hooks/layout/useWindow.ts
- src/hooks/settings/useLogs.ts
> refactor: cache files location for portable

- src/components/settings/Settings.tsx
- src/types/navigation.ts
> fix(settings): incorrect docs link opened via settings sidebar

- CHANGELOG.md
- src-tauri/src/settings.rs
- src-tauri/src/trading_cards.rs
- src/components/contexts/UserContext.tsx
- src/components/settings/TradingCardManagerSettings.tsx
- src/hooks/trading-cards/useTradingCardsList.ts
- src/i18n/locales/en-US/translation.json
- src/types/settings.ts
> refactor(trading-card-manager): use custom interval when selling cards
